### ISSUE TITLE
Number of steps required to train without speaker const loss on large dataset

### ISSUE THREAD

**Issue by skol101** [ConsistencyVC/ConsistencyVC-voive-conversion#25]
Hello,

I've decided to train on vctk+libritts+esd joint dataset to see whether it works better than QuickVC in A2M scenario. For now vctk only training, QuickVC shows much better SMOS that CVC. 

Now, here you recommend to train to 100k for VCTK dataset. I assume it´d require more than 100k initial steps when dataset is enlarged with libritts and ESD? If yes, then by how many more steps?

**Comment by ConsistencyVC** [comment]
For the first question, QuickVC shows much better SMOS that CVC, I guess it is because the whisper encoder output still have some speaker information. So if your study is not related to cross-lingual, Hubert-soft+Data-augmentation is better;
For the second question, yes, larger dataset needs more steps. About when to stop, a good choice is listen to the sample on the tensorboard to decide.
Another advice, CVC is based on VITS, which is a small TTS model, so the training dataset is too big or have too many speakers may affect the speaker similarity.

**Comment by skol101** [comment]
Thank you!
